### ISSUE TITLE
readthedocs VOLTTRON open ADR

### ISSUE THREAD

**Issue by bbartling** [eclipse-volttron/volttron-openadr-ven#39]
Is this the old open ADR agent prior to the make over with open Leadr? if it is should this be removed from readthedocs?

https://volttron.readthedocs.io/en/main/volttron-topics/volttron-applications/openadr-vtn/index.html

**Comment by bonicim** [comment]
Yes, that's old documentation. That lives on monolith Volttron; I've opened up a ticket in that repo and linked this issue to that new issue at https://github.com/VOLTTRON/volttron/issues/3063
